//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure
    {
        public Measure()
        {
            this.PantryItem = new HashSet<PantryItem>();
            this.RecipeItem = new HashSet<RecipeItem>();
        }
    
        public int ID { get; set; }
        public string Measurement { get; set; }
        public string Singular { get; set; }
        public string Plural { get; set; }
    
        public virtual ICollection<PantryItem> PantryItem { get; set; }
        public virtual ICollection<RecipeItem> RecipeItem { get; set; }
    }
}
