//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeItem = new HashSet<RecipeItem>();
            this.PlannedRecipe = new HashSet<PlannedRecipe>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Serves { get; set; }
        public Nullable<int> Calories { get; set; }
        public Nullable<int> PrepTime { get; set; }
        public Nullable<int> Rating { get; set; }
        public string ImagePath { get; set; }
        public string Directions { get; set; }
        public string TagString { get; set; }
    
        public virtual ICollection<RecipeItem> RecipeItem { get; set; }
        public virtual ICollection<PlannedRecipe> PlannedRecipe { get; set; }
    }
}
